version: '2'
services:
  mariadb_base:
    image: docker.io/library/mariadb:10.6
    volumes:
      - 'mariadb_base:/var/lib/mysql'
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
      - MARIADB_DATABASE=test
      - MARIADB_REPLICATION_USER=repl
      - MARIADB_REPLICATION_PASSWORD=replica
      - MARIADB_MYSQL_LOCALHOST_USER=1
    command: --log-bin=mariadb --server-id=100 --sync-binlog=1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
  mariadb_target:
    image: docker.io/library/mariadb:10.11
    volumes:
      - 'mariadb_target:/var/lib/mysql'
    depends_on:
      mariadb_base:
        condition: service_healthy
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_MASTER_HOST=mariadb_base
      - MARIADB_REPLICATION_USER=repl
      - MARIADB_REPLICATION_PASSWORD=replica
      - MARIADB_MYSQL_LOCALHOST_USER=1
      - MARIADB_MYSQL_LOCALHOST_GRANTS=REPLICA MONITOR
    command: --server-id=200 --port 3307
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--innodb_initialized", "--replication_io", "--replication_sql", "--replication_seconds_behind_master=5", "--replication"]
      interval: 10s
      timeout: 5s
      retries: 3
  mariadb_recording:
    image: docker.io/library/mariadb:10.6
    volumes:
      - 'mariadb_recording:/var/lib/mysql'
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=recording
      - MARIADB_PASSWORD=record
      - MARIADB_DATABASE=scary
    command: --port 3308
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
#  kafka:
#    image: 'bitnami/kafka:latest'
#    environment:
#      - ALLOW_PLAINTEXT_LISTENER=yes
  workload:
    image: docker.io/tpcorg/hammerdb:maria
    volumes:
      - type: bind
        source: ./workload_scripts
        target: /mnt
    environment:
      - LOGS=/tmp
      - MARIADB_HOST=mariadb_base
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
      - MARIADB_DATABASE=test
    depends_on:
      mariadb_base:
        condition: service_healthy
      mariadb_recording:
        condition: service_healthy
    command: ./hammerdbcli auto /mnt/maria_tproch.tcl
volumes:
  mariadb_base:
    driver: local
  mariadb_target:
    driver: local
  mariadb_recording:
    driver: local
